include:
  - ditto-services.yml

services:

  gateway:
      image: docker.io/eclipse/ditto-gateway:${DITTO_VERSION:-latest}
      restart: unless-stopped
      networks:
        default:
          aliases:
            - ditto-cluster
      depends_on:
        - policies
      ports:
        - "8081:8080"
      environment:
        - TZ=UTC
        - BIND_HOSTNAME=0.0.0.0
        - ENABLE_PRE_AUTHENTICATION=true
        - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=2 -XX:+ExitOnOutOfMemoryError -XX:+UseContainerSupport -XX:+UseStringDeduplication -Xss512k -XX:MaxRAMPercentage=50 -XX:+UseG1GC -XX:MaxGCPauseMillis=150 -Dpekko.coordinated-shutdown.exit-jvm=on -Dpekko.cluster.shutdown-after-unsuccessful-join-seed-nodes=180s -Dpekko.cluster.failure-detector.threshold=15.0 -Dpekko.cluster.failure-detector.expected-response-after=10s -Dpekko.cluster.failure-detector.acceptable-heartbeat-pause=20s -Dpekko.cluster.downing-provider-class=
      healthcheck:
        test: curl --fail `hostname`:7626/alive || exit 1
        interval: 30s
        timeout: 15s
        retries: 4
        start_period: 120s
      logging:
        options:
          max-size: 50m
