# Copyright (c) 2019 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0

include:
  - ditto-services.yml
  - ditto-gateway.yml

services:

  ditto-ui:
    image: docker.io/eclipse/ditto-ui:${DITTO_VERSION:-latest}
    restart: unless-stopped
    logging:
      options:
        max-size: 10m

  swagger-ui:
    image: docker.io/swaggerapi/swagger-ui:v5.9.1
    environment:
      - QUERY_CONFIG_ENABLED=true
    volumes:
       - ${HOST_WORKSPACE_FOLDER:-../..}/assets/ditto/openapi:/usr/share/nginx/html/openapi:ro
       - ${HOST_WORKSPACE_FOLDER:-../..}/assets/ditto/swagger3-index.html:/usr/share/nginx/html/index.html:ro
    command: nginx -g 'daemon off;'
    logging:
      options:
        max-size: 10m

  nginx:
    image: docker.io/nginx:1.27-alpine
    restart: unless-stopped
    volumes:
       - ${HOST_WORKSPACE_FOLDER:-../..}/assets/ditto/nginx.conf:/etc/nginx/nginx.conf:ro
       - ${HOST_WORKSPACE_FOLDER:-../..}/assets/ditto/nginx.htpasswd:/etc/nginx/nginx.htpasswd:ro
       - ${HOST_WORKSPACE_FOLDER:-../..}/assets/ditto/nginx-cors.conf:/etc/nginx/nginx-cors.conf:ro
       - ${HOST_WORKSPACE_FOLDER:-../..}/assets/ditto/mime.types:/etc/nginx/mime.types:ro
       - ${HOST_WORKSPACE_FOLDER:-../..}/assets/ditto/index.html:/etc/nginx/html/index.html:ro
    ports:
      - "${DITTO_EXTERNAL_PORT:-8080}:80"
    depends_on:
      - gateway
      - swagger-ui
    logging:
      options:
        max-size: 10m
